[build]
  command = "cp package-frontend.json package.json && [ -f .env.production ] && cp .env.production .env || echo 'No .env.production found' && npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"
  VITE_API_URL = "https://web-production-54d13.up.railway.app"

[[redirects]]
  from = "/api/*"
  to = "https://web-production-54d13.up.railway.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
