[build]
  command = "npm run Frontend-build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.4"
  VITE_API_URL= "https://escrow-production-3aaf.up.railway.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
